#!/bin/bash

# Prompt the user to enter a phrase
read -p "Enter a phrase: " phrase

# Count the number of words
word_count=$(echo "$phrase" | wc -w)

# Count the number of spaces
space_count=$(grep -o ' ' <<< "$phrase" | wc -l)

# Print the results
echo "Number of words: $word_count"
echo "Number of spaces: $space_count"

